# Generated by Django 4.0.3 on 2022-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banco', models.CharField(max_length=40)),
                ('Nrocuenta', models.IntegerField()),
                ('Moneda', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nrocomitente', models.IntegerField()),
                ('perfilriesgo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('nacimiento', models.DateTimeField()),
            ],
        ),
    ]
